[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["full", "node-bindings"] }
clap = { version = "4.5.26", features = ["derive"] }
eyre = "0.6.12"
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
